name: Make TWRP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        temp-reserve-mb: 2048
        swap-size-mb: 8192
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - name: Set Variables
      run: echo "{name}=date::$(date +%F)" >> $GITHUB_OUTPUT
    - name: Prepare Environment
      run: |
        export HOME=${GITHUB_WORKSPACE}
        cd ${GITHUB_WORKSPACE}
        sudo apt -y install git aria2 
        git clone https://gitlab.com/OrangeFox/misc/scripts
        cd scripts
        bash setup/android_build_env.sh
        bash setup/install_android_sdk.sh || true
    - name: Init Repo
      run: |
        mkdir ${GITHUB_WORKSPACE}/workspace
        cd ${GITHUB_WORKSPACE}/workspace
        git config --global user.name "RITEFANG"
        git config --global user.email "1721985272@qq.com"
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
    - name: Repo Sync
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        repo sync -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
    - name: Repopick Patches
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        sed -i '/<remove-project name="platform\/external\/gflags"  \/>/d' ${GITHUB_WORKSPACE}/workspace/.repo/manifests/remove-minimal.xml
        sed -i '/<project path="bootable\/recovery" name="android_bootable_recovery" remote="TeamWin" revision="android-12.1"\/>/d' ${GITHUB_WORKSPACE}/workspace/.repo/manifests/twrp-default.xml
        sed -i 's/<project name="android_hardware_qcom_bootctrl" path="hardware\/qcom-caf\/bootctrl" remote="LineageOS" revision="lineage-19.1-caf" \/>/<project name="android_hardware_qcom_bootctrl" path="hardware\/qcom-caf\/bootctrl" remote="LineageOS" revision="lineage-20.0-caf" \/>/g' ${GITHUB_WORKSPACE}/workspace/.repo/manifests/twrp-default.xml
        mv ${GITHUB_WORKSPACE}/workspace/bootable/recovery ${GITHUB_WORKSPACE}/workspace/bootable/recovery-ofrp
        repo sync
        mv ${GITHUB_WORKSPACE}/workspace/bootable/recovery-ofrp ${GITHUB_WORKSPACE}/workspace/bootable/recovery
        cd ${GITHUB_WORKSPACE}
        git clone https://github.com/ymdzq/scripts of_patch
        cd ${GITHUB_WORKSPACE}/workspace/bootable/recovery
        git fetch https://github.com/sekaiacg/twrp_recovery android-12.1 && git cherry-pick 3ce052f
        git apply ${GITHUB_WORKSPACE}/of_patch/early-translation.patch
        git apply ${GITHUB_WORKSPACE}/of_patch/fastbootd-optimize.patch
        git apply ${GITHUB_WORKSPACE}/of_patch/Backup_Display_Name.patch
        git apply ${GITHUB_WORKSPACE}/of_patch/5743.patch
        git apply ${GITHUB_WORKSPACE}/of_patch/DST.patch
        git apply ${GITHUB_WORKSPACE}/of_patch/settings.patch
        git apply ${GITHUB_WORKSPACE}/of_patch/AVB20.patch
        git apply ${GITHUB_WORKSPACE}/of_patch/Update_Log_File.patch
        git apply ${GITHUB_WORKSPACE}/of_patch/Set_FBE_Status.patch
        git apply ${GITHUB_WORKSPACE}/of_patch/Unmount-data.patch
        source build/envsetup.sh
    - name: Clone Device Tree
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        git clone https://github.com/RITEFANG/device_xiaomi_unicorn-twrp-orfp-12.1.git -b main ./device/xiaomi/unicorn
    - name: Building
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        source build/envsetup.sh
        lunch twrp_unicorn-eng
        mka recoveryimage -j$(nproc --all)
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: unicorn_twrp
        path: workspace/out/target/product/unicorn/recovery.img
